[package]
name = "twetch-sdk"
version = "0.0.1"
authors = ["Harry @1"]
edition = "2018"
description = "rust twetch sdk with wasm builds"
license = "MIT"
categories = ['no-std']

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bsv-wasm = "1.0.0"
wasm-bindgen = { version = "0.2.73", features = ["serde-serialize"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.20"

[build-dependencies]
cc = "1.0"
cargo-web = "0.6.26"

[build]
rustflags = ["-C", "target-feature=+simd128"]

[profile.release]
opt-level = 3
lto = true

[profile.test]
opt-level = 3
debug = false
